# Generated by Django 6.0.7 on 2026-08-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SovConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', models.CharField(default='IT', max_length=8)),
                ('meta_reach_since', models.DateField(blank=True, null=True)),
                ('meta_reach_period_days', models.PositiveIntegerField(default=14)),
                ('serp_keywords', models.JSONField(blank=True, default=list)),
                ('meta_access_token', models.CharField(blank=True, max_length=600)),
                ('serpapi_key', models.CharField(blank=True, max_length=200)),
                ('last_meta_run', models.DateField(blank=True, null=True)),
                ('backfill_done_since', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SOV configuration',
                'verbose_name_plural': 'SOV configuration',
            },
        ),
        migrations.CreateModel(
            name='SovRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('cron', 'Cron'), ('import', 'Import')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=10)),
                ('skip', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='competitor',
            name='meta_page_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='meta_search_terms',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='competitor',
            name='trustpilot_slug',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='MetaAdState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_archive_id', models.CharField(max_length=40, unique=True)),
                ('first_seen', models.DateField()),
                ('last_seen', models.DateField()),
                ('active', models.BooleanField(default=False)),
                ('start_time', models.CharField(blank=True, max_length=40)),
                ('stop_time', models.CharField(blank=True, max_length=40)),
                ('reach', models.BigIntegerField(default=0)),
                ('spend_mid', models.FloatField(blank=True, null=True)),
                ('impressions_mid', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_ads', to='competitors.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True)),
                ('metric', models.CharField(db_index=True, max_length=60)),
                ('value', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_points', to='competitors.competitor')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='competitors.sovrun')),
            ],
            options={
                'ordering': ['run_date', 'competitor_id', 'metric'],
                'constraints': [models.UniqueConstraint(fields=('run_date', 'competitor', 'metric', 'note'), name='competitor_metric_point_unique')],
            },
        ),
    ]
