# Generated by Django 6.0.7 on 2026-08-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_sovconfig_sovrun_competitor_meta_page_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sovrun',
            name='legacy_wundt_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trafficupload',
            name='legacy_wundt_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
