# Generated by Django 6.0.7 on 2026-07-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tables_seen', models.JSONField(blank=True, default=list)),
                ('records_new', models.PositiveIntegerField(default=0)),
                ('records_seen', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AirbyteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(db_index=True, help_text='Prefixed stream name, e.g. "fb_ads_insights".', max_length=200)),
                ('ab_id', models.CharField(max_length=64)),
                ('emitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-emitted_at'],
                'unique_together': {('stream', 'ab_id')},
            },
        ),
    ]
