# Generated by Django 6.0.7 on 2026-07-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_marketingevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbyterecord',
            name='ab_id',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='marketingevent',
            name='scope',
            field=models.CharField(blank=True, help_text='Free text reference only — e.g. "meta", "google, sito", "landing". Shown on every chart, does not filter.', max_length=200),
        ),
    ]
