# Generated by Django 6.0.7 on 2026-07-28 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_airbyterecord_ab_id_alter_marketingevent_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FunnelKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('count', 'Numero'), ('eur', 'Euro'), ('percent', 'Percentuale'), ('ratio', 'Rapporto')], default='count', max_length=10)),
                ('target_value', models.FloatField(blank=True, help_text='Obiettivo opzionale, mostrato come riferimento sul grafico.', null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='dashboard.funnelstage')),
            ],
            options={
                'ordering': ['stage__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FunnelStageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('campaign', 'Campagna'), ('ad_set', 'Ad set'), ('channel', 'Canale'), ('other', 'Altro')], default='campaign', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='dashboard.funnelstage')),
            ],
            options={
                'ordering': ['stage__order', 'kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FunnelKPIValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='dashboard.funnelkpi')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('kpi', 'date')},
            },
        ),
    ]
