# Generated by Django 6.0.7 on 2026-07-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_seed_default_funnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelstagesource',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID Meta reale (campaign_id / adset_id / ad_id) per collegare le statistiche esatte. Vuoto per voci non Meta (es. "Altro").', max_length=100),
        ),
        migrations.AlterField(
            model_name='funnelstagesource',
            name='kind',
            field=models.CharField(choices=[('campaign', 'Campagna'), ('ad_set', 'Ad set'), ('ad', 'Ad'), ('channel', 'Canale'), ('other', 'Altro')], default='campaign', max_length=20),
        ),
    ]
