# Generated by Django 6.0.7 on 2026-07-29 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_funnelstagesource_external_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_budget', models.FloatField(default=0, help_text='Budget media totale del periodo, in euro.')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ChannelCadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('target_min', models.FloatField(help_text='Minimo di uscite attese nel periodo.')),
                ('target_max', models.FloatField(blank=True, help_text='Massimo, se è un intervallo.', null=True)),
                ('period', models.CharField(choices=[('week', 'Settimana'), ('month', 'Mese')], default='week', max_length=10)),
                ('role', models.CharField(blank=True, help_text='Ruolo del canale nel funnel.', max_length=250)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Colore hex, es. #f96a34.', max_length=7)),
                ('target_share', models.FloatField(blank=True, help_text="Quota % attesa dentro la sua dimensione. Vuoto se non c'è uno split previsto.", null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dimension__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TagDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Se attivo, una campagna/contenuto può portare più tag di questa dimensione (es. "Bisogno"). Altrimenti se ne aspetta uno solo (es. "Audience").')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('channel', models.CharField(help_text='Deve combaciare con ChannelCadence.channel.', max_length=40)),
                ('content_format', models.CharField(choices=[('reel', 'Reel'), ('post', 'Post'), ('carosello', 'Carosello'), ('story', 'Story'), ('video', 'Video'), ('statico', 'Statico'), ('email', 'Email'), ('altro', 'Altro')], default='post', max_length=20)),
                ('planned_date', models.DateField(db_index=True)),
                ('published_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('idea', 'Idea'), ('brief', 'Brief'), ('produzione', 'In produzione'), ('pronto', 'Pronto'), ('pubblicato', 'Pubblicato'), ('archiviato', 'Archiviato')], db_index=True, default='idea', max_length=20)),
                ('owner', models.CharField(blank=True, help_text='Chi lo produce (social, designer, tutor...).', max_length=120)),
                ('brief', models.TextField(blank=True)),
                ('hook', models.CharField(blank=True, help_text='Come il brand è riconoscibile nei primi 2 secondi (regola creativa della strategia).', max_length=300)),
                ('external_permalink', models.URLField(blank=True, help_text='Link al post pubblicato, per agganciare le metriche reali.')),
                ('external_post_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_source', models.ForeignKey(blank=True, help_text='Campagna/ad set Meta a cui questa creatività è associata, se è un contenuto paid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pieces', to='dashboard.funnelstagesource')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pieces', to='dashboard.funnelstage')),
                ('tags', models.ManyToManyField(blank=True, related_name='content_pieces', to='dashboard.tag')),
            ],
            options={
                'ordering': ['-planned_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('percent', models.FloatField(blank=True, help_text='% del budget totale del piano.', null=True)),
                ('amount', models.FloatField(blank=True, help_text='Importo fisso in euro (alternativo alla %).', null=True)),
                ('is_media', models.BooleanField(default=True, help_text='Disattiva per voci che sono effort operativo e non budget media (es. CRM), così non entrano nella somma del 100%.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, help_text='Campagna/ad set Meta reale, per confrontare pianificato e speso.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='dashboard.funnelstagesource')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_lines', to='dashboard.funnelstage')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dashboard.budgetplan')),
                ('tags', models.ManyToManyField(blank=True, related_name='budget_lines', to='dashboard.tag')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='funnelstagesource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sources', to='dashboard.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dashboard.tagdimension'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('dimension', 'slug')},
        ),
    ]
