# Generated by Django 6.0.7 on 2026-07-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_budgetplan_channelcadence_tag_tagdimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funnelkpi',
            name='aggregation',
            field=models.CharField(choices=[('sum', 'Somma'), ('avg', 'Media'), ('ratio', 'Rapporto pesato (num. ÷ den.)')], default='sum', max_length=10),
        ),
        migrations.AddField(
            model_name='funnelkpi',
            name='entity_level',
            field=models.CharField(blank=True, help_text='Solo per fonte "paid": limita il calcolo a un livello preciso (campaign / ad_set / ad). Vuoto = qualunque livello assegnato alla fase.', max_length=20),
        ),
        migrations.AddField(
            model_name='funnelkpi',
            name='metric',
            field=models.CharField(blank=True, help_text='Metrica di origine (es. impressions, reach, spend). Vedi METRIC_REGISTRY in views.py.', max_length=60),
        ),
        migrations.AddField(
            model_name='funnelkpi',
            name='metric_denominator',
            field=models.CharField(blank=True, help_text='Solo per aggregazione "rapporto": la metrica al denominatore (es. spend ÷ leads = CPL).', max_length=60),
        ),
        migrations.AddField(
            model_name='funnelkpi',
            name='scale',
            field=models.FloatField(default=1.0, help_text='Moltiplicatore applicato al risultato, es. 100 per trasformare un rapporto in percentuale.'),
        ),
        migrations.AddField(
            model_name='funnelkpi',
            name='source',
            field=models.CharField(choices=[('manual', 'Manuale'), ('paid', 'Meta paid (campagne/adset/ad)'), ('organic', 'Post organici'), ('wundt', 'CRM wundt')], default='manual', help_text='Da dove arrivano i numeri. "Manuale" usa i valori inseriti a mano.', max_length=10),
        ),
        migrations.CreateModel(
            name='TaggedEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('campaign', 'Campagna'), ('ad_set', 'Ad set'), ('ad', 'Ad')], db_index=True, max_length=20)),
                ('external_id', models.CharField(db_index=True, help_text='ID Meta reale.', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_entities', to='dashboard.funnelstage')),
                ('tags', models.ManyToManyField(blank=True, related_name='tagged_entities', to='dashboard.tag')),
            ],
            options={
                'ordering': ['kind', 'id'],
                'unique_together': {('kind', 'external_id')},
            },
        ),
    ]
