# Generated by Django 6.0.7 on 2026-08-24 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_comparepreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('identity_mode', models.CharField(choices=[('aggregate_only', 'Aggregate snapshots only'), ('pseudonymous_events', 'Pseudonymous subject events'), ('external_id', 'Clear external CRM ID')], default='pseudonymous_events', max_length=30)),
                ('api_key_hash', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('events', 'Events'), ('snapshots', 'Snapshots')], max_length=20)),
                ('records_received', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_stale', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_logs', to='dashboard.analyticssource')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime'), ('enum', 'Enum')], max_length=20)),
                ('role', models.CharField(choices=[('dimension', 'Dimension'), ('measure', 'Measure'), ('identifier', 'Identifier')], max_length=20)),
                ('sensitivity', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('pseudonymous', 'Pseudonymous'), ('prohibited', 'Prohibited')], default='internal', max_length=20)),
                ('aggregation', models.CharField(choices=[('none', 'None'), ('sum', 'Sum'), ('count', 'Count'), ('distinct', 'Distinct'), ('min', 'Min'), ('max', 'Max')], default='none', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('enum_values', models.JSONField(blank=True, default=list)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.ForeignKey(blank=True, help_text='Null means the definition is shared by every source.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='dashboard.analyticssource')),
            ],
            options={
                'ordering': ['namespace', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source__isnull', False)), fields=('source', 'namespace', 'name'), name='field_source_namespace_name_unique'), models.UniqueConstraint(condition=models.Q(('source__isnull', True)), fields=('namespace', 'name'), name='field_shared_namespace_name_unique')],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_key', models.CharField(max_length=240)),
                ('as_of', models.DateTimeField(db_index=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('measures', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='dashboard.analyticssource')),
            ],
            options={
                'ordering': ['as_of', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('source', 'snapshot_key'), name='metric_snapshot_source_key_unique')],
            },
        ),
        migrations.CreateModel(
            name='SubjectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('external_subject_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('measures', models.JSONField(blank=True, default=dict)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='dashboard.analyticssource')),
            ],
            options={
                'ordering': ['occurred_at', 'pk'],
                'indexes': [models.Index(fields=['source', 'event_type', 'occurred_at'], name='dashboard_s_source__d42ac5_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'event_id'), name='subject_event_source_id_unique')],
            },
        ),
    ]
