# Generated by Django 6.0.7 on 2026-08-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_analyticssource_ingestionlog_fielddefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpiece',
            name='external_origin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='external_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='planned_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='workflow_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='contentpiece',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('external_origin', ''), _negated=True), models.Q(('external_ref', ''), _negated=True)), fields=('external_origin', 'external_ref'), name='content_external_origin_ref_unique'),
        ),
    ]
