# Generated by Django 6.0.7 on 2026-08-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_contentpiece_external_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpiece',
            name='canonical_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EditorialChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_origin', models.CharField(max_length=60)),
                ('external_ref', models.CharField(max_length=200)),
                ('version', models.PositiveIntegerField()),
                ('operation', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_log', to='dashboard.contentpiece')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
